# Generated by Django 5.2.11 on 2026-02-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='co2',
            new_name='co',
        ),
    ]
