# Generated by Django 5.2.11 on 2026-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_rename_co2_measurement_co'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom')], max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('co', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='point',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom')], default='living_room', max_length=20),
            preserve_default=False,
        ),
    ]
