# Generated by Django 5.2.11 on 2026-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alarm_measurement_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='co',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='co',
        ),
        migrations.AddField(
            model_name='alarm',
            name='co_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='co_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='co_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='co_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pressure',
            field=models.FloatField(default=1013.25),
            preserve_default=False,
        ),
    ]
