# Generated by Django 5.2.11 on 2026-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_remove_alarm_co_remove_measurement_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='co',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='co',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
