# Generated by Django 5.2.11 on 2026-04-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_alarm_co_measurement_co'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='co_status',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='point',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='co_status',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='point',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom')], db_index=True, max_length=20),
        ),
    ]
